<a href="https://colab.research.google.com/github/mani-krishna/YBIFoundation/blob/main/ybi_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Women Cloths Reviews ***

---



# **Objectives**
1. **Data Import and Exploration**:
    - Import the dataset and understand its structure.
    - Load and display the dataset.
    - Check data types and missing values.

2. **Data Cleaning**:
    - Handle missing values in the dataset.
    - Replace missing values in the 'Review' column with the mode.

3. **Feature Selection and Target Definition**:
    - Define features (X) as 'Review' and target (y) as 'Rating'.

4. **Data Preprocessing**:
    - Split the dataset into training and testing sets.
    - Convert 'Review' text into numerical tokens using `CountVectorizer`.

5. **Model Training**:
    - Train a `MultinomialNB` model to predict ratings.

6. **Model Evaluation**:
    - Evaluate the model using a confusion matrix and classification report.

7. **Binary Classification (Optional)**:
    - Re-categorize ratings into two classes: poor (0) and good (1).
    - Repeat train-test split, feature conversion, model training, and evaluation for binary classification.

# **Import Library**

In [86]:
import pandas as pd

In [87]:
import numpy as np

In [88]:
import matplotlib.pyplot as plt

In [89]:
import seaborn as sns

# **Import Dataset**

In [90]:
df = pd.read_csv('https://github.com/YBIFoundation/ProjectHub-MachineLearning/raw/main/Women%20Clothing%20E-Commerce%20Review.csv')

***Head ***

In [91]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

***Information ***

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


**Shape number of rows,cols**

In [93]:
df.shape

(23486, 10)

# **Missing Values**

 **Remove missing values in Reviews columns with No Review text**

In [94]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [95]:
df[df['Review']==""]=np.NaN

In [96]:
df['Review'].fillna(df['Review'].mode()[0],inplace=True)

In [97]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [98]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# **Define Target(y) and Feature(X)**

In [99]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [100]:
x = df['Review']

In [101]:
y = df['Rating']

In [102]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# **Train Test Split**

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, stratify = y, random_state = 2529)

In [105]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [106]:
from sklearn.feature_extraction.text import CountVectorizer

In [107]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3),stop_words='english', max_features = 5000)

In [108]:
X_train = cv.fit_transform(X_train)

In [109]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'yellow color',
       'yoga pants', 'zipper little'], dtype=object)

In [110]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [111]:
X_test = cv.transform(X_test)

In [112]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'yellow color',
       'yoga pants', 'zipper little'], dtype=object)

In [113]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Get Model Train**

In [114]:
from sklearn.naive_bayes import MultinomialNB

In [115]:
model = MultinomialNB()

In [116]:
model.fit(X_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [117]:
y_pred = model.predict(X_test)

In [118]:
y_pred.shape

(7046,)

In [119]:
y_pred

array([2, 5, 5, ..., 5, 5, 5])

# **Get Probability of Each predicted Class**

In [152]:
model.predict_proba(X_test)

array([[4.48396994e-01, 5.51603006e-01],
       [2.46650029e-04, 9.99753350e-01],
       [2.05585147e-01, 7.94414853e-01],
       ...,
       [2.79176370e-04, 9.99720824e-01],
       [2.74455042e-05, 9.99972554e-01],
       [1.78653319e-01, 8.21346681e-01]])

# **Get Model Evaluation**

In [121]:
from sklearn.metrics import confusion_matrix, classification_report


In [122]:
print(confusion_matrix(y_test, y_pred))

[[  31   44   54   31   93]
 [  29   98  140   71  132]
 [  19  110  284  200  248]
 [  14   59  197  389  864]
 [  23   57  159  450 3250]]


In [124]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.27      0.12      0.17       253
           2       0.27      0.21      0.23       470
           3       0.34      0.33      0.34       861
           4       0.34      0.26      0.29      1523
           5       0.71      0.83      0.76      3939

    accuracy                           0.58      7046
   macro avg       0.38      0.35      0.36      7046
weighted avg       0.54      0.58      0.55      7046



# **Recategories Ratings as poor (0) and Good (1)**

In [125]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Re-Rating as 1,2,3 as 0 and, 4,5 as 1**

In [126]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace = True)

In [127]:
y = df['Rating']

In [128]:
X = df['Review']

# **Train Test Split**

In [129]:
from sklearn.model_selection import train_test_split

In [132]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, stratify = y, random_state = 2529)

In [133]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape


((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [134]:
from sklearn.feature_extraction.text import CountVectorizer

In [138]:
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features=5000)

In [140]:
X_train = cv.fit_transform(X_train)

In [141]:
X_test = cv.transform(X_test)

# **Get Model Re-Train**

In [143]:
from sklearn.naive_bayes import MultinomialNB

In [144]:
model = MultinomialNB()

In [145]:
model.fit(X_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [146]:
y_pred = model.predict(X_test)

In [147]:
y_pred.shape


(7046,)

In [148]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

# **Get Model Evaluation**

In [149]:
from sklearn.metrics import confusion_matrix, classification_report

In [150]:
print(confusion_matrix(y_test, y_pred))

[[ 911  672]
 [ 550 4913]]


In [151]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.58      0.60      1583
           1       0.88      0.90      0.89      5463

    accuracy                           0.83      7046
   macro avg       0.75      0.74      0.74      7046
weighted avg       0.82      0.83      0.82      7046

